### PR TITLE
Fix mesh creation in islandDetectionAndRemoving, solves #207

### PR DESCRIPTION
**Pull request by TwentyPast4**
Fixes issue #207

### CODE REVIEW

**Comment by nvidia-bgaldrikian** [comment]
Hi, just wanted to let you know that I am looking into this, and working on a solution that will hopefully work for your case as well as the test integration I have in our omni.blast kit integration.  Currently the latter works only without your pull request.

**Comment by nvidia-bgaldrikian** [comment]
Unfortunately your solution did not work when I did Island splitting on the depth-0 chunk.  I found that a much simpler fix handled both your test case and mine (see attached image).  Please let me know if this works for your as well, if so I'll push it through the channels to the public repo.

Thank you!
Bryan

image

**Comment by TwentyPast4** [comment]
> Unfortunately your solution did not work when I did Island splitting on the depth-0 chunk. I found that a much simpler fix handled both your test case and mine (see attached image). Please let me know if this works for your as well, if so I'll push it through the channels to the public repo.
> 
> Thank you! Bryan
> 
> image

Hi, thanks for looking into this.
Your solution works for me as well!

**Comment by nvidia-bgaldrikian** [comment]
Great to hear, I'll get that pushed up the chain.

Thanks again,
Bryan

**Pull request closed without merging**
